### PR TITLE
add .fork option

### PR DESCRIPTION
**Pull request by juliangruber**

### CODE REVIEW

**Comment by mafintosh** [comment]
2.5.0

**Comment by 01binary** [comment]
@juliangruber can you explain why the `fork` option tries to find a node module instead of an executable?

This seems like an API-breaking change:

- Without `fork` option (default): command is a path to an executable file (.exe on Windows)
- With `fork` option: command is a path to a JavaScript file that will be run with node as a module

We use `respawn` to launch using different node versions, so the addition of `fork` option now attempts to load `node.exe` or `node64.exe` as a node module. I get a JavaScript parse error that the .exe is not a JavaScript file.

i.e. we go

`c:\program files\custom-node\node64.exe ourmodule.js`

and it loads

`c:\program files\custom-node\node64.exe` as a node module instead of loading `ourmodule.js` through the specified node exe

Anything can be done about this, PR etc?

**Comment by 01binary** [comment]
See https://github.com/mafintosh/respawn/issues/21

**Comment by juliangruber** [comment]
That's how `child_process.fork` works, see https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options. It needs the path to a node module instead of an executable.

If `{fork:false}`, this is using `child_process.spawn` just as before.

**Comment by 01binary** [comment]
Thanks - just confusing because setting one flag in options changes the API almost entirely.

**Pull request merged**
