### PR TITLE
Add name field to monitor

### PR DESCRIPTION
**Pull request by AlexanderElias**

### CODE REVIEW

**Comment by mafintosh** [comment]
:+1: curious what your use-case is for this?

**Comment by mafintosh** [comment]
2.3.0

**Comment by AlexanderElias** [comment]
Well I am making a node process manager similar to forever but instead of cmd interface it will have a dedicated node API interface. Also the name field will be used to reference an array list of monitors that are kept in memory. 

I thinking it would be even better if every time a monitor was spawned it accomplished this task in the Respawn module.

I was planning on making a pull request to add a Respawn.list() or Respawn.monitors() method. That would just return a array of useable monitor objects. Would something like this be approved?

PS Respawn is a solid module nice work.

**Comment by mafintosh** [comment]
sounds cool!

i'm not sure how .list would work since this is just creating a single monitor instance?

**Comment by AlexanderElias** [comment]
Yeah I think it it would only require a slight reconfiguration. Just need to change the the way that the module is interacted with. 

Example:  

   Respawn.monitor(['node', 'app.js', options]);

I will make a pull request for it.

**Pull request merged**
