### PR TITLE
fixed crash count not adding correctly

### PR DESCRIPTION
**Pull request by AlexanderElias**
Foolish me changed from using ++ to +1.

### CODE REVIEW

**Comment by mafintosh** [comment]
Maybe just `this.crashes++` instead?

**Comment by AlexanderElias** [comment]
Sure I will change it right now.

**Comment by AlexanderElias** [comment]
Do you want me to change the version?

**Comment by AlexanderElias** [comment]
I also just removed the crashes delete because when it is zero it will still not show. Because it evaluates to true.

```JavaScript
var crashes = 0;
if (!crashes) console.log('!crashes is true and will be deleted');
```

**Comment by mafintosh** [comment]
this is perfect, thanks!

**Comment by mafintosh** [comment]
2.4.1

**Pull request merged**
